services:
  flask:
    build: .
    command: gunicorn -b 0.0.0.0:8000 --log-level=info app:app
    ports:
      - "8000:8000"
    environment:
      - PRIVATE_KEY=miniwhores
      - INIT_PUBLIC_KEY=asdf
    depends_on:
      - redis
  worker:
    build: .
    command: python worker.py
    depends_on:
      - redis
  redis:
    image: redis:7.0.12
    volumes:
      - redis-data:/data

volumes:
  redis-data:
