services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PRIVATE_KEY=miniwhores
      - INIT_PUBLIC_KEY=asdf
    depends_on:
      - redis
  
  redis:
    image: redis:7.0.12
