services:
  fastapi:
    build: .
    command: uvicorn --host 0.0.0.0 --port 8000 app:app
    ports:
      - "8000:8000"
    environment:
      - PRIVATE_KEY=miniwhores
      - INIT_PUBLIC_KEY=asdf
    depends_on:
      - redis
  
  redis:
    image: redis:7.0.12
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  default:
    external: true
    name: scoobydoo
