services:
  flask:
    build: .
    network_mode: "host"
    volumes:
      - .:/workspace
    environment:
      - PRIVATE_KEY=miniwhores
      - INIT_PUBLIC_KEY=asdf
    depends_on:
      - redis
  worker:
    build: .
    network_mode: "host"
    command: python worker.py
    volumes:
      - .:/workspace
    depends_on:
      - redis
  redis:
    image: redis:7.0.12
    ports:
      - 6379:6379
