name: Rebuild and Deploy Services

on:
  push:
    branches:
      - main

jobs:
  rebuild-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout latest main
        uses: actions/checkout@v3

      - name: Bring down service
        run: docker compose down

      - name: Rebuild containers and bring up service
        run: docker compose up -d --build
