name: Rebuild and Deploy Services

on:
  push:
    branches:
      - main

jobs:
  rebuild-deploy:
    runs-on: self-hosted

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3

      - name: Bring down service
        working-directory: /home/gagan/gagan-bet
        run: docker compose down

      - name: Pull latest changes
        working-directory: /home/gagan/gagan-bet
        run: |
          git reset --hard HEAD
          git pull
      
      - name: Build frontend
        working-directory: /home/gagan/gagan-bet/frontend
        run: |
          npm install
          npm run build
      
      - name: Build containers and bring up service
        working-directory: /home/gagan/gagan-bet
        run: docker compose up -d --build
